server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bimvr?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: bimvr55@
    filters: wall,mergeStat
    data-source-name: beta
  redis:
    host: 127.0.0.1
    port: 6379
    password: bimvr55@
logging:
  config: classpath:log/logback-spring.xml
  path: F:/log/bimvr

# 沙箱账号
pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016101000653972
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNbi/FdTpWE5abfkF+JMfM2hC/w0D4hPF1eLbK+rZRO2bjlfK23KQaFP7tIDnwGMZT5zQWwdpFXdUTUhysoToMONhSmn5/UZPMWJ635+0nhMey5dsrb6JmdfACAk0O81ExFOMCQQp4qJKKEY8nFO/X8WNneTlKHuh47WfG41raVxDj+fhinUZDRYoGmhL3x/1DwGSJKhKKmY4NDCPoPtCOoLqXznHHDcvCBDj70lzFcWtcYAPPjxKK++SOKFilU7XwO8UMf902KhCqhotOXp5P2rpVePMj4oWko1SKAZRC/L3r4k3n79L2h2Eoa9r+JOSgsZg7VHKdU6ofFWMpccMvAgMBAAECggEBAIGYhzPD4MnBN0+SmMbTQzZGV/SwIVfY0j0XeUB0Dh5PdU90Nq0zbzfrJ1H4Jr8IpKt7f7Kevbi0a6xBoL7bGgrbB/ZhVSqrgOhOCFpyrlB5Dliy4Wti5whGZ8Afhab+dNap0f5dxQ+dQHI99tQUDlbs/W5ymXl+6vzsZhzMdpL8umTjjwo04XJtTvfZe7wGdtFzbVlDeCLzKVhCD2slGyqMKNOaCfRV1EoNfK1xKYn5Jdnqylwq3U5e5D8vfxZ1vEt90O6zFHmytM1gpAgNQE0OgPE0+7uXus2xjNE/ikxyddAAXe5ScvzLMLc4H0XiS+TxhrAZfVIoEeEOhqv0U8kCgYEAv/PEUmaf54dcGGVbDzpdaNiK9LrLWPY2L/3+iqqFUBxhHDZAo102QPKPH6TcyKcUJQpiToy+77hFE3COMxuPFbDAihqTvbShowkFsNvSPTWD3BeiL6es0T0mYVeaCr2p6nUquAz5FUKAXx1CFIk7ZzFQHclRtEKxmI6MNVEiTVMCgYEAvJ7u7EJe3TRYGlMx3G8M8iBRKduFl6QR8dsmi+W5Kvwwug110zqbDaKTBGV3dNuxpHu0fu0dbuXYXhXObyic8HzS9GZ7mUocNC8EWFLemcOZQRl2wlK/MKp/16JC7ehsmkmpaVkDDiONeYoc8jCUYLpJY+VtkfC8l5xpGy4QGzUCgYB3NC/4KCknhGUJ9W+ePlWh9dAdeR8tKQGvviFkBc9yV51rAroTeaBmpvuA4EYICdI1yoQQWdF9V0b2cpCsZnHuO2zmluinB9TVRZYWJf0i6+fuN3MN+ygUbNA35UoRX4V0x7x2vf+1Vy4XYzkVPb/5LqOdS9eEhWJ65hNmTPNrZwKBgHS8KEIwEWX1r1EbjBBQ6kIvngu5wMRI1pJIf2K1mhPwYHfFPNatvqiBpVtjMLsx/I8/wEWNmlm4BmC0Pj6tc/OiTSzVAEmuhCYHszi2kO25EHApwkYh0BHec6CQ27tBzXTvgdmhLTLi7fv6bk+1oR78K8+XfmiEBTQPqT0ZFP7BAoGAHcdxSXv2z5vFu6LD1LozyosH+peDLMQNHZG0nVmxt0Pg1Y+Bpm3Gfr/tSkS0sWR5rKu108bMVUteQMRjpmgzm+Hnz38cY/xL6fNPhkxFfOSlFTFI3mUHxXyj+Ka1q7v6QKjMSYFDAupAbs28qw5hTUisBYer0/sprK3hNje9hmw=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtxwonTjmWZwMltgsGvS+o61Dp2hzGIl4xLlzAGYpyJmR7zZlRCTizkMaewfhiO27e+p4h5wyktXzgHRVT+aawGIt+LbkSvBu1NuDqLYKOFAM/pprx2jUvs/B5SheyIw5SLpHAiHjmF72uFblVKrBcqbn1J7BDwPi31c79IGDEbRUEyM5AD/1gYkBmniOBZu8fWcwUUHGo4/8PmPMmWs3mfB2NoTlxTKAEN7rFD9QK0JMrUqbUriw3BLE5oMxtIzibT5kmj4V+Ty7DlYOku+3c17EUMnhfXP49xpYaPZcd27H59QXG5S5HtqzzY0CKa2IFKUN3IMlfUTb3JpbZ0ezoQIDAQAB
    returnUrl: http://21z9804m0.zicp.vip
    notifyUrl: http://3wpmhu.natappfree.cc/alipay/notify
